sh ./scripts/distributions/batchStrongScaling_64threads_large_distributions.bash
sh ./scripts/distributions/batchStrongScaling_64threads_large_distributions_cpma.bash
sh ./scripts/distributions/batchStrongScaling_64threads_large_distributions_parallelBST.bash