sh ./scripts/finalExperiments/insertion/noProfiler/batchStrongScaling_64threads_large_distributions.bash
sh ./scripts/finalExperiments/insertion/noProfiler/batchStrongScaling_64threads_large_distributions_cpma.bash
sh ./scripts/finalExperiments/insertion/noProfiler/batchStrongScaling_64threads_large_distributions_parallelBST.bash